general:
  logs_path: "./logs.log"
  mlruns_path: "file:/path/to/mlruns"
data:
  order_path: "./Data/order.csv"
  product_path: "./Data/product.csv"
features:
  features_path: "./consumers_features.parquet.gzip"
model:
  model_path: "trained_model.pkl"
  pipeline_path: "training_pipeline.pkl"
  kmeans:
    model_mapping_key: "kmeans"
    pipeline:
      standard_scaling: 
        - 'recency'
        - 'total_baskets'
        - 'total_spend_money'
        - 'total_refund_money'
        - 'total_net_revenue'
        - 'average_basket_spend'
        - 'total_items_purchased'
        - 'total_distinct_items_purchased'
        - 'total_returned_items'
      one_hot_encoding:
        favourite_metal:
          - "0"
          - "1"
          - "10"
          - "13"
          - "15"
          - "16"
          - "17"
          - "22"
          - "23"
          - "24"
          - "25"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
        favourite_store_type:
          - "Concept Store"
          - "Online"
          - "Shop In Shop"
      pca_features:
        - 'recency'
        - 'total_baskets'
        - 'total_spend_money'
        - 'total_refund_money'
        - 'total_net_revenue'
        - 'average_basket_spend'
        - 'total_items_purchased'
        - 'total_distinct_items_purchased'
        - 'total_returned_items'
    params:
      model_params:
        n_clusters: 3
      pca_n_components: 5  # Set to null to use all components
      random_state: 42
mlflow: 
  mlflow_experiment_name: "Customer Segmentation"